name: tos
description: Example of using TIKI for on-chain consent of Terms of Service
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  url_launcher: ^6.1.6
  tiki_sdk_flutter:
    path: ../../../tiki-sdk-flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true