name: docs

on:
  push:
    branches:
      - main

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter TOS Example
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs flutter/tos/README.md flutter/tos/README.md --key=${{ secrets.README_API_KEY }}